[default]
loglevel = "INFO"

#DexSwap default value
chain_id = 1
wallet_address = ""
private_key = ""

block_explorer_api =  ""
block_explorer_url = ""
rpc = ""
protocol_type = "1inch"
router_contract_addr = "0x1F98431c8aD98523631AE4a59f267346ea31F984" #uniswap v3 factory

#📝tokenlist
token_mainnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/all.json"
token_testnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/testnet.json"
token_personal_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/TT.json"

#📝trading token setup
trading_quote_ccy = "USDT"
trading_risk_amount = 10

#📝apollo API
apollo_spot_api_key = ""
apollo_spot_api_secret = ""

apollo_future_api_key = ""
apollo_future_api_secret = ""

[testing]
loglevel = "DEBUG"