[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "definitely"
version = "0.0.1"
authors = [
  { name="MrAniki", email="@MrAniki@mastodon.social" },
]
description = "A defi package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/mraniki/definitely"
"Bug Tracker" = "https://github.com/mraniki/definitely/issues"