[tool.poetry]
name = "dxsp"
version = "0.1.1"
description = "DXSP (DeX SwaP), A defi swap helper package. Swap made easy."
authors = ["mraniki <8766259+mraniki@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
web3 = "^6.1.0"
pycoingecko = "^3.1.0"
python-doten = "^1.0.0"
asyncio ="^3.4.3"
python-semantic-release = "7.33.2"

[tool.poetry.dev-dependencies]
python-semantic-release = "^7.33.2"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "dxsp/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = "pip install poetry && poetry build"