[tool.poetry]
name = "dxsp"
version = "0.0.0"
description = "DXSP (DeX SwaP), A defi swap helper package. Swap made easy."
authors = ["mraniki <8766259+mraniki@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
web3 = ">=6.*"
pycoingecko = "*"
python-dotenv = "*"
asyncio ="*"
python-semantic-release = "*"

[tool.poetry.dev-dependencies]
python-semantic-release = "*"
python-dotenv = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = ["pyproject.toml:version"]
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = "pip install poetry && poetry build"
