name: "📦 Latest"

on:
  push:
    branches:
      - "main"
    tags:
      - "latest"

jobs:
  tagged-release:
    name: "Latest Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}