
name: 🐍Build Python Package

on:
  push:
    branches: [ "main","dev"]
  pull_request:
   branches: [ "main","dev"]
   paths-ignore:
    - "docs/**"
    - "examples/**"
    - "*.md"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Add emoji
      uses: tiena2cva/action-emoji@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip twine
    #     pip install poetry
    #     poetry install
    #     poetry install -E all
    # - name: Build package
    #   run: poetry build

  # test:
  #   - name: Generate coverage report
  #     run: |
  #       pip install pytest
  #       pip install pytest-cov
  #       pytest --cov=./dxsp --cov-report=xml

  #   - name: Upload coverage reports to Codecov
  #     uses: codecov/codecov-action@v3
  #     with:
  #       token: ${{ secrets.CODECOV_TOKEN }}
